### ISSUE TITLE
Feedback 2

### ISSUE THREAD

**Issue by bursteinalan** [CS521-Burstein/final-project-huangyinbuedu#2]
- You have extra files (.idea, Deadline, Requirement); I don't see the value of any of these files. You should remove them from Git and make sure they are in a .gitignore
- Deliverable 2 not met

**Comment by wincyH** [comment]
Wrong File had been uploaded, so that Please review one more time.

**Comment by bursteinalan** [comment]
- You have some extra files (Like a folder named Housing), just check and clean up the repository
- I really like the idea of using the age of the home
- Make sure you know what you are doing (why polynomial of degree 4?)
- I'm confused on your filtering, are you using the median ie throwing away half of the data? The median is the best point to keep. You should instead throw away the extreme values
- Overall good start, make sure to find more visuals that help explain the data and relationships you want to use

**Comment by wincyH** [comment]
Removed extra files.
